/*
weather.gov API

weather.gov API

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GridpointQuantitativeValueLayerValuesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GridpointQuantitativeValueLayerValuesInner{}

// GridpointQuantitativeValueLayerValuesInner struct for GridpointQuantitativeValueLayerValuesInner
type GridpointQuantitativeValueLayerValuesInner struct {
	ValidTime ISO8601Interval `json:"validTime"`
	Value NullableFloat32 `json:"value"`
}

type _GridpointQuantitativeValueLayerValuesInner GridpointQuantitativeValueLayerValuesInner

// NewGridpointQuantitativeValueLayerValuesInner instantiates a new GridpointQuantitativeValueLayerValuesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGridpointQuantitativeValueLayerValuesInner(validTime ISO8601Interval, value NullableFloat32) *GridpointQuantitativeValueLayerValuesInner {
	this := GridpointQuantitativeValueLayerValuesInner{}
	this.ValidTime = validTime
	this.Value = value
	return &this
}

// NewGridpointQuantitativeValueLayerValuesInnerWithDefaults instantiates a new GridpointQuantitativeValueLayerValuesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGridpointQuantitativeValueLayerValuesInnerWithDefaults() *GridpointQuantitativeValueLayerValuesInner {
	this := GridpointQuantitativeValueLayerValuesInner{}
	return &this
}

// GetValidTime returns the ValidTime field value
func (o *GridpointQuantitativeValueLayerValuesInner) GetValidTime() ISO8601Interval {
	if o == nil {
		var ret ISO8601Interval
		return ret
	}

	return o.ValidTime
}

// GetValidTimeOk returns a tuple with the ValidTime field value
// and a boolean to check if the value has been set.
func (o *GridpointQuantitativeValueLayerValuesInner) GetValidTimeOk() (*ISO8601Interval, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidTime, true
}

// SetValidTime sets field value
func (o *GridpointQuantitativeValueLayerValuesInner) SetValidTime(v ISO8601Interval) {
	o.ValidTime = v
}

// GetValue returns the Value field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *GridpointQuantitativeValueLayerValuesInner) GetValue() float32 {
	if o == nil || o.Value.Get() == nil {
		var ret float32
		return ret
	}

	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GridpointQuantitativeValueLayerValuesInner) GetValueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// SetValue sets field value
func (o *GridpointQuantitativeValueLayerValuesInner) SetValue(v float32) {
	o.Value.Set(&v)
}

func (o GridpointQuantitativeValueLayerValuesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GridpointQuantitativeValueLayerValuesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["validTime"] = o.ValidTime
	toSerialize["value"] = o.Value.Get()
	return toSerialize, nil
}

func (o *GridpointQuantitativeValueLayerValuesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"validTime",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGridpointQuantitativeValueLayerValuesInner := _GridpointQuantitativeValueLayerValuesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGridpointQuantitativeValueLayerValuesInner)

	if err != nil {
		return err
	}

	*o = GridpointQuantitativeValueLayerValuesInner(varGridpointQuantitativeValueLayerValuesInner)

	return err
}

type NullableGridpointQuantitativeValueLayerValuesInner struct {
	value *GridpointQuantitativeValueLayerValuesInner
	isSet bool
}

func (v NullableGridpointQuantitativeValueLayerValuesInner) Get() *GridpointQuantitativeValueLayerValuesInner {
	return v.value
}

func (v *NullableGridpointQuantitativeValueLayerValuesInner) Set(val *GridpointQuantitativeValueLayerValuesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGridpointQuantitativeValueLayerValuesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGridpointQuantitativeValueLayerValuesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGridpointQuantitativeValueLayerValuesInner(val *GridpointQuantitativeValueLayerValuesInner) *NullableGridpointQuantitativeValueLayerValuesInner {
	return &NullableGridpointQuantitativeValueLayerValuesInner{value: val, isSet: true}
}

func (v NullableGridpointQuantitativeValueLayerValuesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGridpointQuantitativeValueLayerValuesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


