/*
weather.gov API

weather.gov API

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GridpointHazardsValuesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GridpointHazardsValuesInner{}

// GridpointHazardsValuesInner struct for GridpointHazardsValuesInner
type GridpointHazardsValuesInner struct {
	ValidTime ISO8601Interval `json:"validTime"`
	Value []GridpointHazardsValuesInnerValueInner `json:"value"`
}

type _GridpointHazardsValuesInner GridpointHazardsValuesInner

// NewGridpointHazardsValuesInner instantiates a new GridpointHazardsValuesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGridpointHazardsValuesInner(validTime ISO8601Interval, value []GridpointHazardsValuesInnerValueInner) *GridpointHazardsValuesInner {
	this := GridpointHazardsValuesInner{}
	this.ValidTime = validTime
	this.Value = value
	return &this
}

// NewGridpointHazardsValuesInnerWithDefaults instantiates a new GridpointHazardsValuesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGridpointHazardsValuesInnerWithDefaults() *GridpointHazardsValuesInner {
	this := GridpointHazardsValuesInner{}
	return &this
}

// GetValidTime returns the ValidTime field value
func (o *GridpointHazardsValuesInner) GetValidTime() ISO8601Interval {
	if o == nil {
		var ret ISO8601Interval
		return ret
	}

	return o.ValidTime
}

// GetValidTimeOk returns a tuple with the ValidTime field value
// and a boolean to check if the value has been set.
func (o *GridpointHazardsValuesInner) GetValidTimeOk() (*ISO8601Interval, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidTime, true
}

// SetValidTime sets field value
func (o *GridpointHazardsValuesInner) SetValidTime(v ISO8601Interval) {
	o.ValidTime = v
}

// GetValue returns the Value field value
func (o *GridpointHazardsValuesInner) GetValue() []GridpointHazardsValuesInnerValueInner {
	if o == nil {
		var ret []GridpointHazardsValuesInnerValueInner
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *GridpointHazardsValuesInner) GetValueOk() ([]GridpointHazardsValuesInnerValueInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value, true
}

// SetValue sets field value
func (o *GridpointHazardsValuesInner) SetValue(v []GridpointHazardsValuesInnerValueInner) {
	o.Value = v
}

func (o GridpointHazardsValuesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GridpointHazardsValuesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["validTime"] = o.ValidTime
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *GridpointHazardsValuesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"validTime",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGridpointHazardsValuesInner := _GridpointHazardsValuesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGridpointHazardsValuesInner)

	if err != nil {
		return err
	}

	*o = GridpointHazardsValuesInner(varGridpointHazardsValuesInner)

	return err
}

type NullableGridpointHazardsValuesInner struct {
	value *GridpointHazardsValuesInner
	isSet bool
}

func (v NullableGridpointHazardsValuesInner) Get() *GridpointHazardsValuesInner {
	return v.value
}

func (v *NullableGridpointHazardsValuesInner) Set(val *GridpointHazardsValuesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGridpointHazardsValuesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGridpointHazardsValuesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGridpointHazardsValuesInner(val *GridpointHazardsValuesInner) *NullableGridpointHazardsValuesInner {
	return &NullableGridpointHazardsValuesInner{value: val, isSet: true}
}

func (v NullableGridpointHazardsValuesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGridpointHazardsValuesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


