/*
weather.gov API

weather.gov API

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ZoneCollectionGeoJsonAllOfFeatures type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ZoneCollectionGeoJsonAllOfFeatures{}

// ZoneCollectionGeoJsonAllOfFeatures struct for ZoneCollectionGeoJsonAllOfFeatures
type ZoneCollectionGeoJsonAllOfFeatures struct {
	Properties *Zone `json:"properties,omitempty"`
}

// NewZoneCollectionGeoJsonAllOfFeatures instantiates a new ZoneCollectionGeoJsonAllOfFeatures object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewZoneCollectionGeoJsonAllOfFeatures() *ZoneCollectionGeoJsonAllOfFeatures {
	this := ZoneCollectionGeoJsonAllOfFeatures{}
	return &this
}

// NewZoneCollectionGeoJsonAllOfFeaturesWithDefaults instantiates a new ZoneCollectionGeoJsonAllOfFeatures object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewZoneCollectionGeoJsonAllOfFeaturesWithDefaults() *ZoneCollectionGeoJsonAllOfFeatures {
	this := ZoneCollectionGeoJsonAllOfFeatures{}
	return &this
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *ZoneCollectionGeoJsonAllOfFeatures) GetProperties() Zone {
	if o == nil || IsNil(o.Properties) {
		var ret Zone
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ZoneCollectionGeoJsonAllOfFeatures) GetPropertiesOk() (*Zone, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *ZoneCollectionGeoJsonAllOfFeatures) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given Zone and assigns it to the Properties field.
func (o *ZoneCollectionGeoJsonAllOfFeatures) SetProperties(v Zone) {
	o.Properties = &v
}

func (o ZoneCollectionGeoJsonAllOfFeatures) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ZoneCollectionGeoJsonAllOfFeatures) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	return toSerialize, nil
}

type NullableZoneCollectionGeoJsonAllOfFeatures struct {
	value *ZoneCollectionGeoJsonAllOfFeatures
	isSet bool
}

func (v NullableZoneCollectionGeoJsonAllOfFeatures) Get() *ZoneCollectionGeoJsonAllOfFeatures {
	return v.value
}

func (v *NullableZoneCollectionGeoJsonAllOfFeatures) Set(val *ZoneCollectionGeoJsonAllOfFeatures) {
	v.value = val
	v.isSet = true
}

func (v NullableZoneCollectionGeoJsonAllOfFeatures) IsSet() bool {
	return v.isSet
}

func (v *NullableZoneCollectionGeoJsonAllOfFeatures) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableZoneCollectionGeoJsonAllOfFeatures(val *ZoneCollectionGeoJsonAllOfFeatures) *NullableZoneCollectionGeoJsonAllOfFeatures {
	return &NullableZoneCollectionGeoJsonAllOfFeatures{value: val, isSet: true}
}

func (v NullableZoneCollectionGeoJsonAllOfFeatures) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableZoneCollectionGeoJsonAllOfFeatures) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


