/*
weather.gov API

weather.gov API

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// ZoneState - struct for ZoneState
type ZoneState struct {
	StateTerritoryCode *StateTerritoryCode
	String *string
}

// StateTerritoryCodeAsZoneState is a convenience function that returns StateTerritoryCode wrapped in ZoneState
func StateTerritoryCodeAsZoneState(v *StateTerritoryCode) ZoneState {
	return ZoneState{
		StateTerritoryCode: v,
	}
}

// stringAsZoneState is a convenience function that returns string wrapped in ZoneState
func StringAsZoneState(v *string) ZoneState {
	return ZoneState{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ZoneState) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into StateTerritoryCode
	err = newStrictDecoder(data).Decode(&dst.StateTerritoryCode)
	if err == nil {
		jsonStateTerritoryCode, _ := json.Marshal(dst.StateTerritoryCode)
		if string(jsonStateTerritoryCode) == "{}" { // empty struct
			dst.StateTerritoryCode = nil
		} else {
			if err = validator.Validate(dst.StateTerritoryCode); err != nil {
				dst.StateTerritoryCode = nil
			} else {
				match++
			}
		}
	} else {
		dst.StateTerritoryCode = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.StateTerritoryCode = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ZoneState)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ZoneState)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ZoneState) MarshalJSON() ([]byte, error) {
	if src.StateTerritoryCode != nil {
		return json.Marshal(&src.StateTerritoryCode)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ZoneState) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.StateTerritoryCode != nil {
		return obj.StateTerritoryCode
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableZoneState struct {
	value *ZoneState
	isSet bool
}

func (v NullableZoneState) Get() *ZoneState {
	return v.value
}

func (v *NullableZoneState) Set(val *ZoneState) {
	v.value = val
	v.isSet = true
}

func (v NullableZoneState) IsSet() bool {
	return v.isSet
}

func (v *NullableZoneState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableZoneState(val *ZoneState) *NullableZoneState {
	return &NullableZoneState{value: val, isSet: true}
}

func (v NullableZoneState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableZoneState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


