/*
weather.gov API

weather.gov API

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OfficeHeadlineCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OfficeHeadlineCollection{}

// OfficeHeadlineCollection struct for OfficeHeadlineCollection
type OfficeHeadlineCollection struct {
	Context JsonLdContext `json:"@context"`
	Graph []OfficeHeadline `json:"@graph"`
}

type _OfficeHeadlineCollection OfficeHeadlineCollection

// NewOfficeHeadlineCollection instantiates a new OfficeHeadlineCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOfficeHeadlineCollection(context JsonLdContext, graph []OfficeHeadline) *OfficeHeadlineCollection {
	this := OfficeHeadlineCollection{}
	this.Context = context
	this.Graph = graph
	return &this
}

// NewOfficeHeadlineCollectionWithDefaults instantiates a new OfficeHeadlineCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOfficeHeadlineCollectionWithDefaults() *OfficeHeadlineCollection {
	this := OfficeHeadlineCollection{}
	return &this
}

// GetContext returns the Context field value
func (o *OfficeHeadlineCollection) GetContext() JsonLdContext {
	if o == nil {
		var ret JsonLdContext
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *OfficeHeadlineCollection) GetContextOk() (*JsonLdContext, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Context, true
}

// SetContext sets field value
func (o *OfficeHeadlineCollection) SetContext(v JsonLdContext) {
	o.Context = v
}

// GetGraph returns the Graph field value
func (o *OfficeHeadlineCollection) GetGraph() []OfficeHeadline {
	if o == nil {
		var ret []OfficeHeadline
		return ret
	}

	return o.Graph
}

// GetGraphOk returns a tuple with the Graph field value
// and a boolean to check if the value has been set.
func (o *OfficeHeadlineCollection) GetGraphOk() ([]OfficeHeadline, bool) {
	if o == nil {
		return nil, false
	}
	return o.Graph, true
}

// SetGraph sets field value
func (o *OfficeHeadlineCollection) SetGraph(v []OfficeHeadline) {
	o.Graph = v
}

func (o OfficeHeadlineCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OfficeHeadlineCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["@context"] = o.Context
	toSerialize["@graph"] = o.Graph
	return toSerialize, nil
}

func (o *OfficeHeadlineCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"@context",
		"@graph",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOfficeHeadlineCollection := _OfficeHeadlineCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOfficeHeadlineCollection)

	if err != nil {
		return err
	}

	*o = OfficeHeadlineCollection(varOfficeHeadlineCollection)

	return err
}

type NullableOfficeHeadlineCollection struct {
	value *OfficeHeadlineCollection
	isSet bool
}

func (v NullableOfficeHeadlineCollection) Get() *OfficeHeadlineCollection {
	return v.value
}

func (v *NullableOfficeHeadlineCollection) Set(val *OfficeHeadlineCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableOfficeHeadlineCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableOfficeHeadlineCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOfficeHeadlineCollection(val *OfficeHeadlineCollection) *NullableOfficeHeadlineCollection {
	return &NullableOfficeHeadlineCollection{value: val, isSet: true}
}

func (v NullableOfficeHeadlineCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOfficeHeadlineCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


