/*
weather.gov API

weather.gov API

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ZoneCollectionJsonLd type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ZoneCollectionJsonLd{}

// ZoneCollectionJsonLd struct for ZoneCollectionJsonLd
type ZoneCollectionJsonLd struct {
	Context *JsonLdContext `json:"@context,omitempty"`
	Graph []Zone `json:"@graph,omitempty"`
}

// NewZoneCollectionJsonLd instantiates a new ZoneCollectionJsonLd object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewZoneCollectionJsonLd() *ZoneCollectionJsonLd {
	this := ZoneCollectionJsonLd{}
	return &this
}

// NewZoneCollectionJsonLdWithDefaults instantiates a new ZoneCollectionJsonLd object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewZoneCollectionJsonLdWithDefaults() *ZoneCollectionJsonLd {
	this := ZoneCollectionJsonLd{}
	return &this
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *ZoneCollectionJsonLd) GetContext() JsonLdContext {
	if o == nil || IsNil(o.Context) {
		var ret JsonLdContext
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ZoneCollectionJsonLd) GetContextOk() (*JsonLdContext, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *ZoneCollectionJsonLd) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given JsonLdContext and assigns it to the Context field.
func (o *ZoneCollectionJsonLd) SetContext(v JsonLdContext) {
	o.Context = &v
}

// GetGraph returns the Graph field value if set, zero value otherwise.
func (o *ZoneCollectionJsonLd) GetGraph() []Zone {
	if o == nil || IsNil(o.Graph) {
		var ret []Zone
		return ret
	}
	return o.Graph
}

// GetGraphOk returns a tuple with the Graph field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ZoneCollectionJsonLd) GetGraphOk() ([]Zone, bool) {
	if o == nil || IsNil(o.Graph) {
		return nil, false
	}
	return o.Graph, true
}

// HasGraph returns a boolean if a field has been set.
func (o *ZoneCollectionJsonLd) HasGraph() bool {
	if o != nil && !IsNil(o.Graph) {
		return true
	}

	return false
}

// SetGraph gets a reference to the given []Zone and assigns it to the Graph field.
func (o *ZoneCollectionJsonLd) SetGraph(v []Zone) {
	o.Graph = v
}

func (o ZoneCollectionJsonLd) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ZoneCollectionJsonLd) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Context) {
		toSerialize["@context"] = o.Context
	}
	if !IsNil(o.Graph) {
		toSerialize["@graph"] = o.Graph
	}
	return toSerialize, nil
}

type NullableZoneCollectionJsonLd struct {
	value *ZoneCollectionJsonLd
	isSet bool
}

func (v NullableZoneCollectionJsonLd) Get() *ZoneCollectionJsonLd {
	return v.value
}

func (v *NullableZoneCollectionJsonLd) Set(val *ZoneCollectionJsonLd) {
	v.value = val
	v.isSet = true
}

func (v NullableZoneCollectionJsonLd) IsSet() bool {
	return v.isSet
}

func (v *NullableZoneCollectionJsonLd) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableZoneCollectionJsonLd(val *ZoneCollectionJsonLd) *NullableZoneCollectionJsonLd {
	return &NullableZoneCollectionJsonLd{value: val, isSet: true}
}

func (v NullableZoneCollectionJsonLd) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableZoneCollectionJsonLd) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


