/*
weather.gov API

weather.gov API

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GridpointWeather type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GridpointWeather{}

// GridpointWeather struct for GridpointWeather
type GridpointWeather struct {
	Values []GridpointWeatherValuesInner `json:"values"`
}

type _GridpointWeather GridpointWeather

// NewGridpointWeather instantiates a new GridpointWeather object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGridpointWeather(values []GridpointWeatherValuesInner) *GridpointWeather {
	this := GridpointWeather{}
	this.Values = values
	return &this
}

// NewGridpointWeatherWithDefaults instantiates a new GridpointWeather object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGridpointWeatherWithDefaults() *GridpointWeather {
	this := GridpointWeather{}
	return &this
}

// GetValues returns the Values field value
func (o *GridpointWeather) GetValues() []GridpointWeatherValuesInner {
	if o == nil {
		var ret []GridpointWeatherValuesInner
		return ret
	}

	return o.Values
}

// GetValuesOk returns a tuple with the Values field value
// and a boolean to check if the value has been set.
func (o *GridpointWeather) GetValuesOk() ([]GridpointWeatherValuesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Values, true
}

// SetValues sets field value
func (o *GridpointWeather) SetValues(v []GridpointWeatherValuesInner) {
	o.Values = v
}

func (o GridpointWeather) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GridpointWeather) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["values"] = o.Values
	return toSerialize, nil
}

func (o *GridpointWeather) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"values",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGridpointWeather := _GridpointWeather{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGridpointWeather)

	if err != nil {
		return err
	}

	*o = GridpointWeather(varGridpointWeather)

	return err
}

type NullableGridpointWeather struct {
	value *GridpointWeather
	isSet bool
}

func (v NullableGridpointWeather) Get() *GridpointWeather {
	return v.value
}

func (v *NullableGridpointWeather) Set(val *GridpointWeather) {
	v.value = val
	v.isSet = true
}

func (v NullableGridpointWeather) IsSet() bool {
	return v.isSet
}

func (v *NullableGridpointWeather) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGridpointWeather(val *GridpointWeather) *NullableGridpointWeather {
	return &NullableGridpointWeather{value: val, isSet: true}
}

func (v NullableGridpointWeather) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGridpointWeather) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


