/*
weather.gov API

weather.gov API

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ObservationStationCollectionGeoJsonAllOfFeatures type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObservationStationCollectionGeoJsonAllOfFeatures{}

// ObservationStationCollectionGeoJsonAllOfFeatures struct for ObservationStationCollectionGeoJsonAllOfFeatures
type ObservationStationCollectionGeoJsonAllOfFeatures struct {
	Properties *ObservationStation `json:"properties,omitempty"`
}

// NewObservationStationCollectionGeoJsonAllOfFeatures instantiates a new ObservationStationCollectionGeoJsonAllOfFeatures object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObservationStationCollectionGeoJsonAllOfFeatures() *ObservationStationCollectionGeoJsonAllOfFeatures {
	this := ObservationStationCollectionGeoJsonAllOfFeatures{}
	return &this
}

// NewObservationStationCollectionGeoJsonAllOfFeaturesWithDefaults instantiates a new ObservationStationCollectionGeoJsonAllOfFeatures object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObservationStationCollectionGeoJsonAllOfFeaturesWithDefaults() *ObservationStationCollectionGeoJsonAllOfFeatures {
	this := ObservationStationCollectionGeoJsonAllOfFeatures{}
	return &this
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *ObservationStationCollectionGeoJsonAllOfFeatures) GetProperties() ObservationStation {
	if o == nil || IsNil(o.Properties) {
		var ret ObservationStation
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObservationStationCollectionGeoJsonAllOfFeatures) GetPropertiesOk() (*ObservationStation, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *ObservationStationCollectionGeoJsonAllOfFeatures) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given ObservationStation and assigns it to the Properties field.
func (o *ObservationStationCollectionGeoJsonAllOfFeatures) SetProperties(v ObservationStation) {
	o.Properties = &v
}

func (o ObservationStationCollectionGeoJsonAllOfFeatures) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObservationStationCollectionGeoJsonAllOfFeatures) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	return toSerialize, nil
}

type NullableObservationStationCollectionGeoJsonAllOfFeatures struct {
	value *ObservationStationCollectionGeoJsonAllOfFeatures
	isSet bool
}

func (v NullableObservationStationCollectionGeoJsonAllOfFeatures) Get() *ObservationStationCollectionGeoJsonAllOfFeatures {
	return v.value
}

func (v *NullableObservationStationCollectionGeoJsonAllOfFeatures) Set(val *ObservationStationCollectionGeoJsonAllOfFeatures) {
	v.value = val
	v.isSet = true
}

func (v NullableObservationStationCollectionGeoJsonAllOfFeatures) IsSet() bool {
	return v.isSet
}

func (v *NullableObservationStationCollectionGeoJsonAllOfFeatures) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObservationStationCollectionGeoJsonAllOfFeatures(val *ObservationStationCollectionGeoJsonAllOfFeatures) *NullableObservationStationCollectionGeoJsonAllOfFeatures {
	return &NullableObservationStationCollectionGeoJsonAllOfFeatures{value: val, isSet: true}
}

func (v NullableObservationStationCollectionGeoJsonAllOfFeatures) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObservationStationCollectionGeoJsonAllOfFeatures) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


