/*
weather.gov API

weather.gov API

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PointJsonLd type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PointJsonLd{}

// PointJsonLd struct for PointJsonLd
type PointJsonLd struct {
	Context JsonLdContext `json:"@context"`
	// A geometry represented in Well-Known Text (WKT) format.
	Geometry NullableString `json:"geometry"`
	Id *string `json:"@id,omitempty"`
	Type *string `json:"@type,omitempty"`
	Cwa *NWSForecastOfficeId `json:"cwa,omitempty"`
	ForecastOffice *string `json:"forecastOffice,omitempty"`
	GridId *NWSForecastOfficeId `json:"gridId,omitempty"`
	GridX *int32 `json:"gridX,omitempty"`
	GridY *int32 `json:"gridY,omitempty"`
	Forecast *string `json:"forecast,omitempty"`
	ForecastHourly *string `json:"forecastHourly,omitempty"`
	ForecastGridData *string `json:"forecastGridData,omitempty"`
	ObservationStations *string `json:"observationStations,omitempty"`
	RelativeLocation *PointRelativeLocation `json:"relativeLocation,omitempty"`
	ForecastZone *string `json:"forecastZone,omitempty"`
	County *string `json:"county,omitempty"`
	FireWeatherZone *string `json:"fireWeatherZone,omitempty"`
	TimeZone *string `json:"timeZone,omitempty"`
	RadarStation *string `json:"radarStation,omitempty"`
}

type _PointJsonLd PointJsonLd

// NewPointJsonLd instantiates a new PointJsonLd object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPointJsonLd(context JsonLdContext, geometry NullableString) *PointJsonLd {
	this := PointJsonLd{}
	this.Context = context
	this.Geometry = geometry
	return &this
}

// NewPointJsonLdWithDefaults instantiates a new PointJsonLd object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPointJsonLdWithDefaults() *PointJsonLd {
	this := PointJsonLd{}
	return &this
}

// GetContext returns the Context field value
func (o *PointJsonLd) GetContext() JsonLdContext {
	if o == nil {
		var ret JsonLdContext
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *PointJsonLd) GetContextOk() (*JsonLdContext, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Context, true
}

// SetContext sets field value
func (o *PointJsonLd) SetContext(v JsonLdContext) {
	o.Context = v
}

// GetGeometry returns the Geometry field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PointJsonLd) GetGeometry() string {
	if o == nil || o.Geometry.Get() == nil {
		var ret string
		return ret
	}

	return *o.Geometry.Get()
}

// GetGeometryOk returns a tuple with the Geometry field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PointJsonLd) GetGeometryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Geometry.Get(), o.Geometry.IsSet()
}

// SetGeometry sets field value
func (o *PointJsonLd) SetGeometry(v string) {
	o.Geometry.Set(&v)
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PointJsonLd) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointJsonLd) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PointJsonLd) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PointJsonLd) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *PointJsonLd) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointJsonLd) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *PointJsonLd) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *PointJsonLd) SetType(v string) {
	o.Type = &v
}

// GetCwa returns the Cwa field value if set, zero value otherwise.
func (o *PointJsonLd) GetCwa() NWSForecastOfficeId {
	if o == nil || IsNil(o.Cwa) {
		var ret NWSForecastOfficeId
		return ret
	}
	return *o.Cwa
}

// GetCwaOk returns a tuple with the Cwa field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointJsonLd) GetCwaOk() (*NWSForecastOfficeId, bool) {
	if o == nil || IsNil(o.Cwa) {
		return nil, false
	}
	return o.Cwa, true
}

// HasCwa returns a boolean if a field has been set.
func (o *PointJsonLd) HasCwa() bool {
	if o != nil && !IsNil(o.Cwa) {
		return true
	}

	return false
}

// SetCwa gets a reference to the given NWSForecastOfficeId and assigns it to the Cwa field.
func (o *PointJsonLd) SetCwa(v NWSForecastOfficeId) {
	o.Cwa = &v
}

// GetForecastOffice returns the ForecastOffice field value if set, zero value otherwise.
func (o *PointJsonLd) GetForecastOffice() string {
	if o == nil || IsNil(o.ForecastOffice) {
		var ret string
		return ret
	}
	return *o.ForecastOffice
}

// GetForecastOfficeOk returns a tuple with the ForecastOffice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointJsonLd) GetForecastOfficeOk() (*string, bool) {
	if o == nil || IsNil(o.ForecastOffice) {
		return nil, false
	}
	return o.ForecastOffice, true
}

// HasForecastOffice returns a boolean if a field has been set.
func (o *PointJsonLd) HasForecastOffice() bool {
	if o != nil && !IsNil(o.ForecastOffice) {
		return true
	}

	return false
}

// SetForecastOffice gets a reference to the given string and assigns it to the ForecastOffice field.
func (o *PointJsonLd) SetForecastOffice(v string) {
	o.ForecastOffice = &v
}

// GetGridId returns the GridId field value if set, zero value otherwise.
func (o *PointJsonLd) GetGridId() NWSForecastOfficeId {
	if o == nil || IsNil(o.GridId) {
		var ret NWSForecastOfficeId
		return ret
	}
	return *o.GridId
}

// GetGridIdOk returns a tuple with the GridId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointJsonLd) GetGridIdOk() (*NWSForecastOfficeId, bool) {
	if o == nil || IsNil(o.GridId) {
		return nil, false
	}
	return o.GridId, true
}

// HasGridId returns a boolean if a field has been set.
func (o *PointJsonLd) HasGridId() bool {
	if o != nil && !IsNil(o.GridId) {
		return true
	}

	return false
}

// SetGridId gets a reference to the given NWSForecastOfficeId and assigns it to the GridId field.
func (o *PointJsonLd) SetGridId(v NWSForecastOfficeId) {
	o.GridId = &v
}

// GetGridX returns the GridX field value if set, zero value otherwise.
func (o *PointJsonLd) GetGridX() int32 {
	if o == nil || IsNil(o.GridX) {
		var ret int32
		return ret
	}
	return *o.GridX
}

// GetGridXOk returns a tuple with the GridX field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointJsonLd) GetGridXOk() (*int32, bool) {
	if o == nil || IsNil(o.GridX) {
		return nil, false
	}
	return o.GridX, true
}

// HasGridX returns a boolean if a field has been set.
func (o *PointJsonLd) HasGridX() bool {
	if o != nil && !IsNil(o.GridX) {
		return true
	}

	return false
}

// SetGridX gets a reference to the given int32 and assigns it to the GridX field.
func (o *PointJsonLd) SetGridX(v int32) {
	o.GridX = &v
}

// GetGridY returns the GridY field value if set, zero value otherwise.
func (o *PointJsonLd) GetGridY() int32 {
	if o == nil || IsNil(o.GridY) {
		var ret int32
		return ret
	}
	return *o.GridY
}

// GetGridYOk returns a tuple with the GridY field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointJsonLd) GetGridYOk() (*int32, bool) {
	if o == nil || IsNil(o.GridY) {
		return nil, false
	}
	return o.GridY, true
}

// HasGridY returns a boolean if a field has been set.
func (o *PointJsonLd) HasGridY() bool {
	if o != nil && !IsNil(o.GridY) {
		return true
	}

	return false
}

// SetGridY gets a reference to the given int32 and assigns it to the GridY field.
func (o *PointJsonLd) SetGridY(v int32) {
	o.GridY = &v
}

// GetForecast returns the Forecast field value if set, zero value otherwise.
func (o *PointJsonLd) GetForecast() string {
	if o == nil || IsNil(o.Forecast) {
		var ret string
		return ret
	}
	return *o.Forecast
}

// GetForecastOk returns a tuple with the Forecast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointJsonLd) GetForecastOk() (*string, bool) {
	if o == nil || IsNil(o.Forecast) {
		return nil, false
	}
	return o.Forecast, true
}

// HasForecast returns a boolean if a field has been set.
func (o *PointJsonLd) HasForecast() bool {
	if o != nil && !IsNil(o.Forecast) {
		return true
	}

	return false
}

// SetForecast gets a reference to the given string and assigns it to the Forecast field.
func (o *PointJsonLd) SetForecast(v string) {
	o.Forecast = &v
}

// GetForecastHourly returns the ForecastHourly field value if set, zero value otherwise.
func (o *PointJsonLd) GetForecastHourly() string {
	if o == nil || IsNil(o.ForecastHourly) {
		var ret string
		return ret
	}
	return *o.ForecastHourly
}

// GetForecastHourlyOk returns a tuple with the ForecastHourly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointJsonLd) GetForecastHourlyOk() (*string, bool) {
	if o == nil || IsNil(o.ForecastHourly) {
		return nil, false
	}
	return o.ForecastHourly, true
}

// HasForecastHourly returns a boolean if a field has been set.
func (o *PointJsonLd) HasForecastHourly() bool {
	if o != nil && !IsNil(o.ForecastHourly) {
		return true
	}

	return false
}

// SetForecastHourly gets a reference to the given string and assigns it to the ForecastHourly field.
func (o *PointJsonLd) SetForecastHourly(v string) {
	o.ForecastHourly = &v
}

// GetForecastGridData returns the ForecastGridData field value if set, zero value otherwise.
func (o *PointJsonLd) GetForecastGridData() string {
	if o == nil || IsNil(o.ForecastGridData) {
		var ret string
		return ret
	}
	return *o.ForecastGridData
}

// GetForecastGridDataOk returns a tuple with the ForecastGridData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointJsonLd) GetForecastGridDataOk() (*string, bool) {
	if o == nil || IsNil(o.ForecastGridData) {
		return nil, false
	}
	return o.ForecastGridData, true
}

// HasForecastGridData returns a boolean if a field has been set.
func (o *PointJsonLd) HasForecastGridData() bool {
	if o != nil && !IsNil(o.ForecastGridData) {
		return true
	}

	return false
}

// SetForecastGridData gets a reference to the given string and assigns it to the ForecastGridData field.
func (o *PointJsonLd) SetForecastGridData(v string) {
	o.ForecastGridData = &v
}

// GetObservationStations returns the ObservationStations field value if set, zero value otherwise.
func (o *PointJsonLd) GetObservationStations() string {
	if o == nil || IsNil(o.ObservationStations) {
		var ret string
		return ret
	}
	return *o.ObservationStations
}

// GetObservationStationsOk returns a tuple with the ObservationStations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointJsonLd) GetObservationStationsOk() (*string, bool) {
	if o == nil || IsNil(o.ObservationStations) {
		return nil, false
	}
	return o.ObservationStations, true
}

// HasObservationStations returns a boolean if a field has been set.
func (o *PointJsonLd) HasObservationStations() bool {
	if o != nil && !IsNil(o.ObservationStations) {
		return true
	}

	return false
}

// SetObservationStations gets a reference to the given string and assigns it to the ObservationStations field.
func (o *PointJsonLd) SetObservationStations(v string) {
	o.ObservationStations = &v
}

// GetRelativeLocation returns the RelativeLocation field value if set, zero value otherwise.
func (o *PointJsonLd) GetRelativeLocation() PointRelativeLocation {
	if o == nil || IsNil(o.RelativeLocation) {
		var ret PointRelativeLocation
		return ret
	}
	return *o.RelativeLocation
}

// GetRelativeLocationOk returns a tuple with the RelativeLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointJsonLd) GetRelativeLocationOk() (*PointRelativeLocation, bool) {
	if o == nil || IsNil(o.RelativeLocation) {
		return nil, false
	}
	return o.RelativeLocation, true
}

// HasRelativeLocation returns a boolean if a field has been set.
func (o *PointJsonLd) HasRelativeLocation() bool {
	if o != nil && !IsNil(o.RelativeLocation) {
		return true
	}

	return false
}

// SetRelativeLocation gets a reference to the given PointRelativeLocation and assigns it to the RelativeLocation field.
func (o *PointJsonLd) SetRelativeLocation(v PointRelativeLocation) {
	o.RelativeLocation = &v
}

// GetForecastZone returns the ForecastZone field value if set, zero value otherwise.
func (o *PointJsonLd) GetForecastZone() string {
	if o == nil || IsNil(o.ForecastZone) {
		var ret string
		return ret
	}
	return *o.ForecastZone
}

// GetForecastZoneOk returns a tuple with the ForecastZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointJsonLd) GetForecastZoneOk() (*string, bool) {
	if o == nil || IsNil(o.ForecastZone) {
		return nil, false
	}
	return o.ForecastZone, true
}

// HasForecastZone returns a boolean if a field has been set.
func (o *PointJsonLd) HasForecastZone() bool {
	if o != nil && !IsNil(o.ForecastZone) {
		return true
	}

	return false
}

// SetForecastZone gets a reference to the given string and assigns it to the ForecastZone field.
func (o *PointJsonLd) SetForecastZone(v string) {
	o.ForecastZone = &v
}

// GetCounty returns the County field value if set, zero value otherwise.
func (o *PointJsonLd) GetCounty() string {
	if o == nil || IsNil(o.County) {
		var ret string
		return ret
	}
	return *o.County
}

// GetCountyOk returns a tuple with the County field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointJsonLd) GetCountyOk() (*string, bool) {
	if o == nil || IsNil(o.County) {
		return nil, false
	}
	return o.County, true
}

// HasCounty returns a boolean if a field has been set.
func (o *PointJsonLd) HasCounty() bool {
	if o != nil && !IsNil(o.County) {
		return true
	}

	return false
}

// SetCounty gets a reference to the given string and assigns it to the County field.
func (o *PointJsonLd) SetCounty(v string) {
	o.County = &v
}

// GetFireWeatherZone returns the FireWeatherZone field value if set, zero value otherwise.
func (o *PointJsonLd) GetFireWeatherZone() string {
	if o == nil || IsNil(o.FireWeatherZone) {
		var ret string
		return ret
	}
	return *o.FireWeatherZone
}

// GetFireWeatherZoneOk returns a tuple with the FireWeatherZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointJsonLd) GetFireWeatherZoneOk() (*string, bool) {
	if o == nil || IsNil(o.FireWeatherZone) {
		return nil, false
	}
	return o.FireWeatherZone, true
}

// HasFireWeatherZone returns a boolean if a field has been set.
func (o *PointJsonLd) HasFireWeatherZone() bool {
	if o != nil && !IsNil(o.FireWeatherZone) {
		return true
	}

	return false
}

// SetFireWeatherZone gets a reference to the given string and assigns it to the FireWeatherZone field.
func (o *PointJsonLd) SetFireWeatherZone(v string) {
	o.FireWeatherZone = &v
}

// GetTimeZone returns the TimeZone field value if set, zero value otherwise.
func (o *PointJsonLd) GetTimeZone() string {
	if o == nil || IsNil(o.TimeZone) {
		var ret string
		return ret
	}
	return *o.TimeZone
}

// GetTimeZoneOk returns a tuple with the TimeZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointJsonLd) GetTimeZoneOk() (*string, bool) {
	if o == nil || IsNil(o.TimeZone) {
		return nil, false
	}
	return o.TimeZone, true
}

// HasTimeZone returns a boolean if a field has been set.
func (o *PointJsonLd) HasTimeZone() bool {
	if o != nil && !IsNil(o.TimeZone) {
		return true
	}

	return false
}

// SetTimeZone gets a reference to the given string and assigns it to the TimeZone field.
func (o *PointJsonLd) SetTimeZone(v string) {
	o.TimeZone = &v
}

// GetRadarStation returns the RadarStation field value if set, zero value otherwise.
func (o *PointJsonLd) GetRadarStation() string {
	if o == nil || IsNil(o.RadarStation) {
		var ret string
		return ret
	}
	return *o.RadarStation
}

// GetRadarStationOk returns a tuple with the RadarStation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointJsonLd) GetRadarStationOk() (*string, bool) {
	if o == nil || IsNil(o.RadarStation) {
		return nil, false
	}
	return o.RadarStation, true
}

// HasRadarStation returns a boolean if a field has been set.
func (o *PointJsonLd) HasRadarStation() bool {
	if o != nil && !IsNil(o.RadarStation) {
		return true
	}

	return false
}

// SetRadarStation gets a reference to the given string and assigns it to the RadarStation field.
func (o *PointJsonLd) SetRadarStation(v string) {
	o.RadarStation = &v
}

func (o PointJsonLd) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PointJsonLd) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["@context"] = o.Context
	toSerialize["geometry"] = o.Geometry.Get()
	if !IsNil(o.Id) {
		toSerialize["@id"] = o.Id
	}
	if !IsNil(o.Type) {
		toSerialize["@type"] = o.Type
	}
	if !IsNil(o.Cwa) {
		toSerialize["cwa"] = o.Cwa
	}
	if !IsNil(o.ForecastOffice) {
		toSerialize["forecastOffice"] = o.ForecastOffice
	}
	if !IsNil(o.GridId) {
		toSerialize["gridId"] = o.GridId
	}
	if !IsNil(o.GridX) {
		toSerialize["gridX"] = o.GridX
	}
	if !IsNil(o.GridY) {
		toSerialize["gridY"] = o.GridY
	}
	if !IsNil(o.Forecast) {
		toSerialize["forecast"] = o.Forecast
	}
	if !IsNil(o.ForecastHourly) {
		toSerialize["forecastHourly"] = o.ForecastHourly
	}
	if !IsNil(o.ForecastGridData) {
		toSerialize["forecastGridData"] = o.ForecastGridData
	}
	if !IsNil(o.ObservationStations) {
		toSerialize["observationStations"] = o.ObservationStations
	}
	if !IsNil(o.RelativeLocation) {
		toSerialize["relativeLocation"] = o.RelativeLocation
	}
	if !IsNil(o.ForecastZone) {
		toSerialize["forecastZone"] = o.ForecastZone
	}
	if !IsNil(o.County) {
		toSerialize["county"] = o.County
	}
	if !IsNil(o.FireWeatherZone) {
		toSerialize["fireWeatherZone"] = o.FireWeatherZone
	}
	if !IsNil(o.TimeZone) {
		toSerialize["timeZone"] = o.TimeZone
	}
	if !IsNil(o.RadarStation) {
		toSerialize["radarStation"] = o.RadarStation
	}
	return toSerialize, nil
}

func (o *PointJsonLd) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"@context",
		"geometry",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPointJsonLd := _PointJsonLd{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPointJsonLd)

	if err != nil {
		return err
	}

	*o = PointJsonLd(varPointJsonLd)

	return err
}

type NullablePointJsonLd struct {
	value *PointJsonLd
	isSet bool
}

func (v NullablePointJsonLd) Get() *PointJsonLd {
	return v.value
}

func (v *NullablePointJsonLd) Set(val *PointJsonLd) {
	v.value = val
	v.isSet = true
}

func (v NullablePointJsonLd) IsSet() bool {
	return v.isSet
}

func (v *NullablePointJsonLd) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePointJsonLd(val *PointJsonLd) *NullablePointJsonLd {
	return &NullablePointJsonLd{value: val, isSet: true}
}

func (v NullablePointJsonLd) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePointJsonLd) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


