/*
weather.gov API

weather.gov API

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// GridpointForecastPeriodTemperature - High/low temperature for the period, depending on whether the period is day or night. This property as an integer value is deprecated. Future versions will express this value as a quantitative value object. To make use of the future standard format now, set the \"forecast_temperature_qv\" feature flag on the request. 
type GridpointForecastPeriodTemperature struct {
	QuantitativeValue *QuantitativeValue
	Int32 *int32
}

// QuantitativeValueAsGridpointForecastPeriodTemperature is a convenience function that returns QuantitativeValue wrapped in GridpointForecastPeriodTemperature
func QuantitativeValueAsGridpointForecastPeriodTemperature(v *QuantitativeValue) GridpointForecastPeriodTemperature {
	return GridpointForecastPeriodTemperature{
		QuantitativeValue: v,
	}
}

// int32AsGridpointForecastPeriodTemperature is a convenience function that returns int32 wrapped in GridpointForecastPeriodTemperature
func Int32AsGridpointForecastPeriodTemperature(v *int32) GridpointForecastPeriodTemperature {
	return GridpointForecastPeriodTemperature{
		Int32: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *GridpointForecastPeriodTemperature) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into QuantitativeValue
	err = newStrictDecoder(data).Decode(&dst.QuantitativeValue)
	if err == nil {
		jsonQuantitativeValue, _ := json.Marshal(dst.QuantitativeValue)
		if string(jsonQuantitativeValue) == "{}" { // empty struct
			dst.QuantitativeValue = nil
		} else {
			if err = validator.Validate(dst.QuantitativeValue); err != nil {
				dst.QuantitativeValue = nil
			} else {
				match++
			}
		}
	} else {
		dst.QuantitativeValue = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.QuantitativeValue = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(GridpointForecastPeriodTemperature)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(GridpointForecastPeriodTemperature)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GridpointForecastPeriodTemperature) MarshalJSON() ([]byte, error) {
	if src.QuantitativeValue != nil {
		return json.Marshal(&src.QuantitativeValue)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GridpointForecastPeriodTemperature) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.QuantitativeValue != nil {
		return obj.QuantitativeValue
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableGridpointForecastPeriodTemperature struct {
	value *GridpointForecastPeriodTemperature
	isSet bool
}

func (v NullableGridpointForecastPeriodTemperature) Get() *GridpointForecastPeriodTemperature {
	return v.value
}

func (v *NullableGridpointForecastPeriodTemperature) Set(val *GridpointForecastPeriodTemperature) {
	v.value = val
	v.isSet = true
}

func (v NullableGridpointForecastPeriodTemperature) IsSet() bool {
	return v.isSet
}

func (v *NullableGridpointForecastPeriodTemperature) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGridpointForecastPeriodTemperature(val *GridpointForecastPeriodTemperature) *NullableGridpointForecastPeriodTemperature {
	return &NullableGridpointForecastPeriodTemperature{value: val, isSet: true}
}

func (v NullableGridpointForecastPeriodTemperature) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGridpointForecastPeriodTemperature) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


