/*
weather.gov API

weather.gov API

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// GridpointForecastPeriodWindSpeed - Wind speed for the period. This property as an string value is deprecated. Future versions will express this value as a quantitative value object. To make use of the future standard format now, set the \"forecast_wind_speed_qv\" feature flag on the request. 
type GridpointForecastPeriodWindSpeed struct {
	QuantitativeValue *QuantitativeValue
	String *string
}

// QuantitativeValueAsGridpointForecastPeriodWindSpeed is a convenience function that returns QuantitativeValue wrapped in GridpointForecastPeriodWindSpeed
func QuantitativeValueAsGridpointForecastPeriodWindSpeed(v *QuantitativeValue) GridpointForecastPeriodWindSpeed {
	return GridpointForecastPeriodWindSpeed{
		QuantitativeValue: v,
	}
}

// stringAsGridpointForecastPeriodWindSpeed is a convenience function that returns string wrapped in GridpointForecastPeriodWindSpeed
func StringAsGridpointForecastPeriodWindSpeed(v *string) GridpointForecastPeriodWindSpeed {
	return GridpointForecastPeriodWindSpeed{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *GridpointForecastPeriodWindSpeed) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into QuantitativeValue
	err = newStrictDecoder(data).Decode(&dst.QuantitativeValue)
	if err == nil {
		jsonQuantitativeValue, _ := json.Marshal(dst.QuantitativeValue)
		if string(jsonQuantitativeValue) == "{}" { // empty struct
			dst.QuantitativeValue = nil
		} else {
			if err = validator.Validate(dst.QuantitativeValue); err != nil {
				dst.QuantitativeValue = nil
			} else {
				match++
			}
		}
	} else {
		dst.QuantitativeValue = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.QuantitativeValue = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(GridpointForecastPeriodWindSpeed)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(GridpointForecastPeriodWindSpeed)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GridpointForecastPeriodWindSpeed) MarshalJSON() ([]byte, error) {
	if src.QuantitativeValue != nil {
		return json.Marshal(&src.QuantitativeValue)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GridpointForecastPeriodWindSpeed) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.QuantitativeValue != nil {
		return obj.QuantitativeValue
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableGridpointForecastPeriodWindSpeed struct {
	value *GridpointForecastPeriodWindSpeed
	isSet bool
}

func (v NullableGridpointForecastPeriodWindSpeed) Get() *GridpointForecastPeriodWindSpeed {
	return v.value
}

func (v *NullableGridpointForecastPeriodWindSpeed) Set(val *GridpointForecastPeriodWindSpeed) {
	v.value = val
	v.isSet = true
}

func (v NullableGridpointForecastPeriodWindSpeed) IsSet() bool {
	return v.isSet
}

func (v *NullableGridpointForecastPeriodWindSpeed) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGridpointForecastPeriodWindSpeed(val *GridpointForecastPeriodWindSpeed) *NullableGridpointForecastPeriodWindSpeed {
	return &NullableGridpointForecastPeriodWindSpeed{value: val, isSet: true}
}

func (v NullableGridpointForecastPeriodWindSpeed) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGridpointForecastPeriodWindSpeed) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


