/*
weather.gov API

weather.gov API

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TextProductCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TextProductCollection{}

// TextProductCollection struct for TextProductCollection
type TextProductCollection struct {
	Context *JsonLdContext `json:"@context,omitempty"`
	Graph []TextProduct `json:"@graph,omitempty"`
}

// NewTextProductCollection instantiates a new TextProductCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTextProductCollection() *TextProductCollection {
	this := TextProductCollection{}
	return &this
}

// NewTextProductCollectionWithDefaults instantiates a new TextProductCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTextProductCollectionWithDefaults() *TextProductCollection {
	this := TextProductCollection{}
	return &this
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *TextProductCollection) GetContext() JsonLdContext {
	if o == nil || IsNil(o.Context) {
		var ret JsonLdContext
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextProductCollection) GetContextOk() (*JsonLdContext, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *TextProductCollection) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given JsonLdContext and assigns it to the Context field.
func (o *TextProductCollection) SetContext(v JsonLdContext) {
	o.Context = &v
}

// GetGraph returns the Graph field value if set, zero value otherwise.
func (o *TextProductCollection) GetGraph() []TextProduct {
	if o == nil || IsNil(o.Graph) {
		var ret []TextProduct
		return ret
	}
	return o.Graph
}

// GetGraphOk returns a tuple with the Graph field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextProductCollection) GetGraphOk() ([]TextProduct, bool) {
	if o == nil || IsNil(o.Graph) {
		return nil, false
	}
	return o.Graph, true
}

// HasGraph returns a boolean if a field has been set.
func (o *TextProductCollection) HasGraph() bool {
	if o != nil && !IsNil(o.Graph) {
		return true
	}

	return false
}

// SetGraph gets a reference to the given []TextProduct and assigns it to the Graph field.
func (o *TextProductCollection) SetGraph(v []TextProduct) {
	o.Graph = v
}

func (o TextProductCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TextProductCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Context) {
		toSerialize["@context"] = o.Context
	}
	if !IsNil(o.Graph) {
		toSerialize["@graph"] = o.Graph
	}
	return toSerialize, nil
}

type NullableTextProductCollection struct {
	value *TextProductCollection
	isSet bool
}

func (v NullableTextProductCollection) Get() *TextProductCollection {
	return v.value
}

func (v *NullableTextProductCollection) Set(val *TextProductCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableTextProductCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableTextProductCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTextProductCollection(val *TextProductCollection) *NullableTextProductCollection {
	return &NullableTextProductCollection{value: val, isSet: true}
}

func (v NullableTextProductCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTextProductCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


